image: docker:dind

services:
  - docker:dind

variables:
  DOCKER_TLS_CERTDIR: "/certs"

stages:
  - info
  - build

info:
  stage: info
  script:
    - docker info

build:
  stage: build
  before_script:
    - echo "$CI_REGISTRY_PASSWORD" | docker login --username "$CI_REGISTRY_USER" --password-stdin registry.gitlab.com
  script:
    - docker build .

